### ISSUE TITLE
wss://ws-mainnet-node.huobichain.com response code: 403

### ISSUE THREAD

**Issue by biluochun** [HuobiGroup/huobi-eco-chain-docs#11]
```javascript
new Web3('wss://ws-mainnet-node.huobichain.com');
// WebSocket connection to 'wss://ws-mainnet-node.huobichain.com/' failed: Error during WebSocket handshake: Unexpected response code: 403
```

**Comment by kevinho** [comment]
i think the usage is incorrect:

```
const Web3 = require('web3')
const www =  new Web3(new Web3.providers.WebsocketProvider("wss://ws-mainnet-node.huobichain.com"));

async function f1(){
    const balance = await www.eth.getBalance("0x03245922d9dc42d12F6d07013146C986a4d0Aa86");
    console.log(balance)
}
f1()
```

**Comment by biluochun** [comment]
WebSocket connection to 'wss://ws-mainnet-node.huobichain.com/' failed: Error during WebSocket handshake: Unexpected response code: 403

> i think the usage is incorrect:
> 
> ```
> const Web3 = require('web3')
> const www =  new Web3(new Web3.providers.WebsocketProvider("wss://ws-mainnet-node.huobichain.com"));
> 
> async function f1(){
>     const balance = await www.eth.getBalance("0x03245922d9dc42d12F6d07013146C986a4d0Aa86");
>     console.log(balance)
> }
> f1()
> ```

**Comment by woshidama323** [comment]
same issue
