### ISSUE TITLE
哪里可以获取到测试链上的HT？

### ISSUE THREAD

**Issue by chenluyong** [HuobiGroup/huobi-eco-chain-docs#16]

**Comment by Nanyan** [comment]
https://docs.hecochain.com/#/testnet

**Comment by xuanzhui** [comment]
授权不成功 application_suspended ，怎么处理，返回的链接

https://scan-testnet.hecochain.com/faucet?error=application_suspended&error_description=Your%20application%20has%20been%20suspended.%20Please%20contact%20support%40github.com.&error_uri=catiohttps%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23applin-suspended
