### ISSUE TITLE
http-testnet.hecochain.com timeout

### ISSUE THREAD

**Issue by H1l4nd0r** [HuobiGroup/huobi-eco-chain-docs#18]
Hi.
I'm trying to deploy token to https://http-testnet.hecochain.com
from truffle with this config
hecotestnet: {
provider: () => new HDWalletProvider(mnemonic,
`https://http-testnet.hecochain.com`),
network_id: 256,
from: '0x6709dBd0870397d613D479d8790AD2d1191F34bA',
skipDryRun: true
},

but i'm getting
Error: There was a timeout while attempting to connect to the network.

but I can ping http-testnet.hecochain.com ad it is ok

what is wrong please help

**Comment by wangsai-silence** [comment]
Try `https://http-testnet.huobichain.com` from [Dev docs](https://docs.hecochain.com/#/testnet)

**Comment by H1l4nd0r** [comment]
> Try `https://http-testnet.huobichain.com` from [Dev docs](https://docs.hecochain.com/#/testnet)

Thank you! this helps
