### ISSUE TITLE
举报诈骗项目MFD

### ISSUE THREAD

**Issue by Gold-pig** [HuobiGroup/huobi-eco-chain-docs#9]
火币heco团队你们好，
举报一个诈骗项目MFD，总共累计诈骗约200万usdt，并且已经转入了火币的地址。
这是诈骗方的地址：
https://hecoinfo.com/address/0xda36e64877b4fae41385cd55a12b79bd1259094b，
近期token转账记录来看，把所有的usdt转入了：https://hecoinfo.com/address/0xdb95801820b5c5eb4e337096a7c6de7bc266a6e9#tokentxns 
并且提现到火币。
骗子创建实施诈骗的合约：
https://hecoinfo.com/token/0x7b8085a07f1c40322f60c06f022c132ecf64d232#balances

我并没有投入太多，但是看到骗子在heco上肆无忌惮，横行市场，诈骗用户，孰不可忍，希望火币能进行调查并且给一个合理的答复。

**Comment by Nanyan** [comment]
Thanks for your report. It was noticed and processed by our relative team. For any further details, please contact the service support.
